services:
  - type: web
    name: robinet-euro
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python3 server.py
    envVars:
      - key: GITHUB_BACKUP_REPO
        value: thomasmartialfrancomme-oss/euro-robinet-data
